---
title: "Tidy Tuesday 2020-01-14 : the passwords dataset"
output: 
  rmarkdown::html_vignette:
    toc: TRUE
vignette: >
  %\VignetteIndexEntry{td_2020-01-14_Passwords}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 5
)
```


```{r setup, warning=FALSE, message=FALSE}
library(nd.tidytuesday)

library(dplyr)
library(ggplot2)
```


## Data import and inspection

```{r data import}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
```


```{r data inspect}
passwords %>% head() %>% pander::pander()
```

One can obtain the metadata table using `datapasta`'s R package addin.

```{r metadata}
meta <- data.frame(stringsAsFactors=FALSE,
                   variable = c("rank", "password", "category", "value", "time_unit",
                                "offline_crack_sec", "rank_alt", "strength", "font_size"),
                   class = c("double", "character", "character", "double", "character",
                             "double", "double", "double", "double"),
                   description = c("popularity in their database of released passwords",
                                   "Actual text of the password",
                                   "What category does the password fall in to?", "Time to crack by online guessing",
                                   "Time unit to match with value", "Time to crack offline in seconds",
                                   "Rank 2", "Strength = quality of password where 10 is highest,
                   1 is lowest,
                   please note that these are relative to these generally bad passwords", "Used to create the graphic for KIB")
)
meta <- as_tibble(meta)

pander::pander(meta)
```

```{r data quality}
passwords %>% 
  glimpse()

# --- using base R function
# passwords %>% 
#   qual_fun(.)

# --- tidyverse approach
passwords %>% 
  tidy_qual() %>% 
  pander::pander()
```

The 7 missing values are the in the same rows :

```{r NA}
passwords %>% 
  filter(!complete.cases(passwords))
```

In total it represents less than 2% of the total of data.

```{r naniar vis}
passwords %>% 
  naniar::vis_miss()

passwords %>% 
  visdat::vis_dat()
```


To fix the types, the character variables are set as factors.

```{r types}
psw_clean <-
  passwords %>% 
  filter(complete.cases(passwords)) %>% 
  mutate_if(is.character, factor)

psw_clean %>% 
  summarise_if(.tbl = .,.predicate = is.factor, .funs = list("nb_u" = ~length(unique(.))) ) %>% 
  mutate(indic = "nb unique") %>% 
  select(indic, everything())
```



```{r category}
cat_stat <- psw_clean %>%
  group_by(category) %>% 
  summarise(nb = n()) %>% 
  arrange(-nb)

cat_stat %>% 
  ggplot(aes(x = forcats::fct_reorder(.f = category, .x = nb), y = nb)) + 
  geom_col(fill = "#4F62DB") +
  geom_text(aes(y = nb + 5, label = nb)) +
  xlab("Category of passord") + ylab("Count") +
  ggtitle("Repartition of the password categories") +
  theme_light() +
  coord_flip()
```

```{r time unit}
tu_stat <- psw_clean %>%
  group_by(time_unit) %>% 
  summarise(nb = n()) %>% 
  arrange(-nb)

tu_stat %>% 
  ggplot(aes(x = forcats::fct_reorder(.f = time_unit, .x = nb), y = nb)) + 
  geom_col(fill = "#D91515") +
  geom_text(aes(y = nb + 10, label = nb)) +
  xlab("Time unit to crack a passord") + ylab("Count") +
  ggtitle("Repartition of the time unit required to crack the concidered passwords") +
  theme_light() +
  coord_flip()
```



```{r}
library(stringr)

passwd_type <- psw_clean %>% 
  mutate(password = as.character(password)) %>% 
  mutate("nb_char" = nchar(password),
         num_part = purrr::map_chr( stringr::str_extract_all(string = password, pattern = "[:digit:]"),
                                    function(x) paste(x, collapse = "") ),
         nchar_num = nchar(num_part),
         
         alpha_part = purrr::map_chr( stringr::str_extract_all(string = password, pattern = "[:alpha:]"),
                                    function(x) paste(x, collapse = "") ),
         nchar_alpha = nchar(alpha_part),
         
         punct_part = purrr::map_chr( stringr::str_extract_all(string = password, pattern = "[:punct:]"),
                                    function(x) paste(x, collapse = "") ),
         nchar_punct = nchar(punct_part),
         
         lower_part = purrr::map_chr( stringr::str_extract_all(string = password, pattern = "[:lower:]"),
                                    function(x) paste(x, collapse = "") ),
         nchar_lower = nchar(lower_part),
         
         upper_part = purrr::map_chr( stringr::str_extract_all(string = password, pattern = "[:upper:]"),
                                    function(x) paste(x, collapse = "") ),
         nchar_upper = nchar(upper_part)
  )

# passwd_type %>% View()
passwd_type %>% # glimpse()
  ggplot(aes(x = value, y = offline_crack_sec, colour = strength, size = factor(nb_char)) ) +
  geom_point(alpha = .1)
  # facet_grid("category", scales = "free")


passwd_type %>%
  filter(value < 25) %>% 
  ggplot(aes(x = value, y = offline_crack_sec, colour = strength, size = nb_char) ) +
  geom_jitter(alpha = .3)

passwd_type %>%
  filter(value > 25) %>% 
  ggplot(aes(x = value, y = offline_crack_sec, colour = strength, size = nb_char) ) +
  geom_jitter(alpha = .3)
```


```{r by type}
passwd_type %>%
  select(dplyr::starts_with("nchar")) %>%
  base_summary()
```


