on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")' \
                  -e 'remotes::install_deps(dependencies = TRUE)' \
                  -e 'remotes::install_github("jimhester/pkgdown@github-actions-deploy")' \
                  -e 'remotes::install_cran("knitr")' \
                  -e 'remotes::install_cran("devtools")'
#      - name: Build package
#        run: R CMD BUILD .
#      - name: Install package
#        run: R CMD INSTALL .
      - name: Check package
#        run: R CMD CHECK .
# following docs recomentation with devtools::check() ( http://r-pkgs.had.co.nz/check.html )
        run: |
          Rscript -e 'devtools::check()'
      - name: render README
        run: |
          Rscript -e 'knitr::render_markdown(README.Rmd)'
      - name: Deploy package
        run: |
          pkgdown:::deploy_local(new_process = TRUE, remote_url = 'https://x-access-token:${{secrets.DEPLOY_PAT}}@github.com/${{github.repository}}.git')
        shell: Rscript {0}
